apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ganache
  template:
    metadata:
      labels:
        app: ganache
    spec:
      containers:
        - name: ganache
          image: harsh/ganache:latest
          resources:
            limits:
              cpu: "250m" # 250 millicores
              memory: "500Mi"
          ports:
            - containerPort: 8545
